# Generated by Django 5.0 on 2024-02-16 13:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='vendor.jpg', upload_to=base.models.use_directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
